# Generated by Django 4.2 on 2023-04-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
